version: '3'
services:
  plugin_store:
    build: .
    container_name: plugin_store
    environment:
        - DB_PATH=/db/plugin_store.db
        - ANNOUNCEMENT_WEBHOOK
        - SUBMIT_AUTH_KEY
        - B2_APP_KEY_ID
        - B2_APP_KEY
        - B2_BUCKET_ID
    volumes:
        - ~/database:/db
    networks:
        - plugins-network
    restart: unless-stopped

networks:
  plugins-network:
    driver: bridge
